[package]
name = "advent_day_1"
version = "0.1.0"
authors = ["p1516523 <tristan.guillard@etu.univ-lyon1.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
